name: firebase_performance_web
description: Web implementation of Firebase Performance monitoring.
homepage: https://github.com/firebase/flutterfire/tree/main/packages/firebase_performance/firebase_performance_web
version: 0.1.8+13
publish_to: 'none'


environment:
  sdk: '^3.13.0'
  flutter: '>=3.47.0'

dependencies:
  firebase_core:
    git: https://github.com/kumsumit/firebase_core.git
  firebase_core_web:
    git: https://github.com/kumsumit/firebase_core_web.git
  firebase_performance_platform_interface:
    git: https://github.com/kumsumit/firebase_performance_platform_interface.git
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutterfire_internals:
    git: https://github.com/kumsumit/flutterfire_internals.git  


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebasePerformanceWeb
        fileName: firebase_performance_web.dart
